const picker=document.getElementById('surfacePicker');
const win=document.querySelector('.window');
const caption=document.getElementById('caption');
const labels={editor:'Editor Focus — the production milestone requested for the first pass.',menu:'Bend application menu — existing file commands moved into compact chrome.',files:'Files — an intentionally empty pane for this milestone.',searchpane:'Repository search — an intentionally empty pane for this milestone.',git:'Source control — an intentionally empty pane for this milestone.',find:'Find and replace — contextual to the active editor.',settings:'Settings — existing options restyled inside the workspace.',goto:'Go to line — compact modal with keyboard-first input.',encoding:'File encoding — selection, risk message, and explicit apply action.',unsaved:'Unsaved changes — three-way save decision.',message:'Alert / confirmation — shared dialog treatment for file and error messages.',tabmenu:'Tab context menu — all current tab operations retained.',editmenu:'Editor context menu — editing, history, go-to, and recording operations retained.',terminal:'Terminal — existing native terminal expanded from its panel header.',drag:'Tab drag feedback — a lightweight ghost matching the new tab.',empty:'Empty editor — useful first-run and all-tabs-closed state.'};
function show(value){win.className='window mode-'+value;document.querySelectorAll('.rail button').forEach(b=>b.classList.remove('active'));if(['files','searchpane','git'].includes(value)){win.classList.add('pane-open');const button=document.querySelector(`[data-pane="${value}"]`);button.classList.add('active');document.getElementById('paneTitle').textContent=value==='searchpane'?'SEARCH':value==='git'?'SOURCE CONTROL':'FILES';}caption.textContent=labels[value];}
picker.addEventListener('change',e=>{if(e.target.value==='settings'){window.location.href='settings.html';return;}show(e.target.value)});
document.querySelectorAll('[data-pane]').forEach(button=>button.addEventListener('click',()=>{picker.value=button.dataset.pane;show(button.dataset.pane)}));
document.getElementById('brand').addEventListener('click',()=>{picker.value='menu';show('menu')});
document.querySelector('.command').addEventListener('click',()=>{picker.value='find';show('find')});
document.querySelector('.settings-close').addEventListener('click',()=>{picker.value='editor';show('editor')});
show('editor');
